# Generated by Django 5.2.4 on 2025-08-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Cloudinary Image URL'),
        ),
    ]
